Artur
L-Marcel/apister pull request #21
Opened 2024-12-22 22:00 UTC by x0cuoxq8w5

closes #16 
closes #14

2024-12-22 23:03 UTC, L-Marcel requested changes
Acredito que deva estar funcionando bem, mas deixei sugestões de melhorias e apontei possíveis problemas. Como estamos com tempo e estas talvez sejam as últimas tarefas dessa atividade, vou estar revisando todas as solicitações.

Desde já, parabéns, está fazendo um bom trabalho.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/controllers/components/ProjectCellController.java
> +            Dialog<String> dialog = new Dialog<String>(
Por favor, trocar de `String` para `Boolean` e realizar as adaptações necessárias. Também estou com um Tic porque você usou dois `if` ao invés deu um `if` e `else`.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/controllers/components/ProjectCellController.java
> +            ObjectOutputStream objectOutputStream;
Não tem pra que declarar `File`, `FileOutputStream` e `ObjectOutputStream` antes de utilizá-lo. Sei que não faz muita diferença, mas acho que fica mais legível declara no momento em que instancia.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/controllers/components/RemoveDialogProjectController.java
> +public class RemoveDialogProjectController extends DialogController<String> implements Initializable {
Trocar de `String` para `Boolean`.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/core/Node.java
> +
Acho que o problema não era o construtor vazio, como conversamos no whatsapp. Logo, peço para que experimente testar novamente removendo esse construtor. Acredito que ele é desnecessário mesmo.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/controllers/ProjectsController.java
> +            Project project = new Project(name,node);
Não precisa salvar em uma variável a instância do `Project`, repare que você nem esta utilizando-a. O uso dela aqui é meramente chamar as funções do construtor dela.

Se estiver com tempo e quiser um desafio, nota: seria interessante mais um `Dialog` para confirmar a importação caso já existe o projeto na lista de projetos. Bom, você já fez um `Dialog` de confirmação, outro seria bem parecido.

2024-12-22 23:03 UTC, L-Marcel commented on src/main/java/app/controllers/ProjectsController.java
> +            Projects.getInstance().add(name);
Independentemente do comentário anterior, não faz sentido adicionar se já existir viu! Isso pode causar duplicação de nomes.

2024-12-23 01:28 UTC, x0cuoxq8w5 commented on src/main/java/app/controllers/components/ProjectCellController.java
> +            ObjectOutputStream objectOutputStream;
Faço isso por preferência (e é até boa prática dependendo, me recordo que é bom declarar as vars primeiro pra poder saber quais são usadas ou algo do tipo (e em C nas versões mais antigas você tem que fazer isso)), mas altero de boa.

2024-12-23 01:35 UTC, x0cuoxq8w5 commented on src/main/java/app/core/Node.java
> +
Eu comentei o construtor vazio e rodei. Exportei um projeto. Explodiu imediatamente ao importar.

2024-12-23 01:46 UTC, x0cuoxq8w5 commented on src/main/java/app/controllers/ProjectsController.java
> +            Project project = new Project(name,node);
Não vejo porque haveria uma confirmação se a gente não vai deixar duplicado; Seria pra esse caso que crie um segundo com o nome com, sei lá [nome do projeto] (1) como com arquivos duplicados no windows?

2024-12-23 10:25 UTC, L-Marcel commented on src/main/java/app/controllers/ProjectsController.java
> +            Project project = new Project(name,node);
Suponha que você exporta o projeto com o nome "Testes". E outra pessoa, que já tem um projeto com esse nome, importa ele. O arquivo vai ser substituído, isso pode até ser um comportamento padrão, mas quando cair na linha `66` o mesmo nome vai ser armazenado na lista em `Projects`, causando duplicidade no `ListView`. 

Uma opção boa que pensei agora é usar o `Dialog` usado para adicionar para importar também, porém abrindo ele com o nome escrito no arquivo, entendeu? Ele já tem essa validação de duplicidade e o usuário poderia mudar o nome.

Mas tem mais de uma forma de resolver esse problema.

2024-12-23 21:47 UTC, L-Marcel approved these changes

2024-12-23 21:55 UTC, L-Marcel approved these changes
Ok, está bem melhor assim. Bom trabalho @x0cuoxq8w5! Ainda farei algumas alterações futuras, mas provavelmente serão apenas de legibilidade. Não realizarei testes agora, pois estou focado em desenvolver o um `Highlighter` e pelo que vi seu código aparenta está totalmente funcional.

Pode descansar, acho que demoraremos para terminar as metas atuais, e talvez elas sejam praticamente as últimas.

> Nota: eu acidentalmente fechei a revisão anterior e abri uma nova, além de fechar e reabri o `pull request`, total inexperiência.

2024-12-23 21:55 UTC, L-Marcel commented on src/main/java/app/controllers/ProjectsController.java
> +            project = null; //solução gambiarra porque eu não tô conseguindo pensar numa solução pra isso agora
Ué, mas não precisava disso, essa linguagem tem `gabage collector`, se esqueceu? kkkkkk

2024-12-23 21:56 UTC, merged